<a href="https://colab.research.google.com/github/paruliansaragi/DL-Notebooks/blob/master/TFA1OpsandLogReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
"""
Simple exercises to get used to TensorFlow API
You should thoroughly test your code.
TensorFlow's official documentation should be your best friend here
CS20: "TensorFlow for Deep Learning Research"
cs20.stanford.edu
Created by Chip Huyen (chiphuyen@cs.stanford.edu)
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

sess = tf.InteractiveSession()
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.greater(x, y), lambda: x + y, lambda: x - y)
print(sess.run(out))

-0.5983182


In [0]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

# YOUR CODE
# So the tf.random_uniform() takes in shape, a minval which we can use as -1 and a maxval as 1)
# Use shape=[] for 0-d tensor when using rand uni
x = tf.random_uniform(shape=[], minval=-1, maxval=1, dtype=tf.float32)#Correct
y = tf.random_uniform(shape=[], minval=-1, maxval=1, dtype=tf.float32)
# Using cond
# tf.cond seems to take in two ternary lambda functions based on the first initial condition
# ret = tf.cond(x < y, lambda: tf.subtract(x, y), lambda: 0)
# Using tf.case()
# takes in a boolean scalar tensor and a python callable that creates the tensors to be returned
# if the bool is True.
def py_callable1(): return tf.add(x, y) #if not a function then returns err
def py_callable2(): return tf.zeros(1)
#out = tf.case({tf.less(x, y): py_callable1, tf.greater(x, y): py_callable2})
#out = tf.case([(tf.less(x, y), py_callable1)], default=py_callable2)
out = tf.case({tf.less(x, y): lambda: tf.add(x, y),
              tf.greater(x, y): lambda: tf.subtract(x,y)},
             default=lambda: tf.constant(0.0), exclusive=True)
print(sess.run(out))

0.23227906


In [0]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

# YOUR CODE
x = tf.constant([[0, -2, -1],[0, 1, 2]], dtype=tf.float32)
y = tf.zeros(shape=[2,3], dtype=tf.float32)
out = tf.equal(x, y) #takes an x tensor and a y tensor and a name and returns a tensor of bools if x == y
print(sess.run(out))

[[ True False False]
 [ True False False]]


In [0]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

# YOUR CODE
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858], dtype=tf.float32)
greater = tf.where(tf.greater(x, 30))#takes in a condition, 
# and x or y and returns elements either from x or y depending on your condition
#tf.gather, gathers slices from params axis, axis according to indices
gathered = tf.gather(x, greater) 
# params: a tensor from which to gather values
# indices: a tensor, 
# axis: axis in params to gather indices from
print(sess.run(gathered))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [0]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

# YOUR CODE
# tf.linalg.diag() returns a bathed diagonal tensor with a given batched diagonal values
# given a diagonal, returns a tensor with the diagonal and everything else padded with zeros
vals = tf.range(1, 7, 1) # should return [1, 2, 3, 4, 5, 6]
# now create a diagonal from those values on the diag and 0 everywhere else
diag = tf.diag(vals)
print(sess.run(diag))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [0]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

# YOUR CODE
rand = tf.random_normal(shape=[10,10], mean=10, stddev=1)
deter = tf.matrix_determinant(rand)#Computes the determinant of one or more square matrices.
print(sess.run(deter))

-13092.184


In [0]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

# YOUR CODE
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
uniq = tf.unique(x) #finds unique elements in a 1-D tensor
# returns a tensor y containing all unique elements of x sorted in the same order they occurred.
# also returns idx tensor that contains index of each value of in output.
# so uniq will be 5:0, 2:1, 3:2 ...
# lets use zip to unpack 
val,idx = uniq
print(sess.run(val))

[ 5  2  3 10  6  4  1  0  9]


In [0]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

# YOUR CODE

x = tf.random_normal(shape=[300], mean=25, stddev=1)
y = tf.random_normal(shape=[300], mean=25, stddev=1)
#tf.reduce_mean() computes the mean of elements across dimensions of a tensor.
# returns a reduced tensor
avg = tf.reduce_mean(x - y)
#tf.reduce_sum() computes the sum of elements across dimensions of a tensor. 
# returns a reduced tensor
def f1(): return tf.reduce_mean(tf.square(x - y))
#tf.abs() computes the absolute value of a tensor (non-zero value). 
def f2(): return tf.reduce_sum(tf.abs(x - y))
out = tf.cond(avg < 0, f1, f2)
print(sess.run(out))

327.55774


In [0]:
!wget https://raw.githubusercontent.com/chiphuyen/stanford-tensorflow-tutorials/master/examples/utils.py

--2019-01-25 09:35:49--  https://raw.githubusercontent.com/chiphuyen/stanford-tensorflow-tutorials/master/examples/utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5167 (5.0K) [text/plain]
Saving to: ‘utils.py’

utils.py            100%[===================>]   5.05K  --.-KB/s    in 0s      

2019-01-25 09:35:49 (83.0 MB/s) - ‘utils.py’ saved [5167/5167]



In [0]:
""" Starter code for simple logistic regression model for MNIST
with tf.data module
MNIST dataset: yann.lecun.com/exdb/mnist/
Created by Chip Huyen (chiphuyen@cs.stanford.edu)
CS20: "TensorFlow for Deep Learning Research"
cs20.stanford.edu
Lecture 03
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import numpy as np
import tensorflow as tf
import time

import utils

# Define paramaters for the model
learning_rate = 0.01
batch_size = 128
n_epochs = 30
n_train = 60000
n_test = 10000

# Step 1: Read in data
mnist_folder = 'data/mnist'
utils.download_mnist(mnist_folder)
train, val, test = utils.read_mnist(mnist_folder, flatten=True)

# Step 2: Create datasets and iterator
# create training Dataset and batch it
train_data = tf.data.Dataset.from_tensor_slices(train)
train_data = train_data.shuffle(10000) # if you want to shuffle your data
train_data = train_data.batch(batch_size)

# create testing Dataset and batch it
# dont shuffle test set
test_data = tf.data.Dataset.from_tensor_slices(test)
test_data = test_data.batch(batch_size)
#############################
########## TO DO ############
#############################

# create one iterator and initialize it with different datasets
iterator = tf.data.Iterator.from_structure(train_data.output_types, 
                                           train_data.output_shapes)
img, label = iterator.get_next()

train_init = iterator.make_initializer(train_data)	# initializer for train_data
test_init = iterator.make_initializer(test_data)	# initializer for train_data

# Step 3: create weights and bias
# w is initialized to random variables with mean of 0, stddev of 0.01
# b is initialized to 0
# shape of w depends on the dimension of X and Y so that Y = tf.matmul(X, w)
# shape of b depends on Y
w = tf.get_variable(name='weights', shape=(784,10), initializer=tf.random_normal_initializer(0, 0.01))
b = tf.get_variable(name='bias', shape=(1,10), initializer=tf.random_zeros_initializer())
#############################
########## TO DO ############
#############################

# Step 4: build model
# the model that returns the logits.
# this logits will be later passed through softmax layer
logits = tf.matmul(img, w) + b
#############################
########## TO DO ############
#############################


# Step 5: define loss function
# use cross entropy of softmax of logits as the loss function
entropy = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=label, name='entropy')
loss = tf.reduce_mean(entropy, name='loss') #computes the mean over all the examples in the batch 
#############################
########## TO DO ############
#############################


# Step 6: define optimizer
# using Adamn Optimizer with pre-defined learning rate to minimize loss
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)
#############################
########## TO DO ############
#############################


# Step 7: calculate accuracy with test set
preds = tf.nn.softmax(logits)
correct_preds = tf.equal(tf.argmax(preds, 1), tf.argmax(label, 1))
accuracy = tf.reduce_sum(tf.cast(correct_preds, tf.float32))

writer = tf.summary.FileWriter('./graphs/logreg', tf.get_default_graph())
with tf.Session() as sess:
   
    start_time = time.time()
    sess.run(tf.global_variables_initializer())

    # train the model n_epochs times
    for i in range(n_epochs): 	
        sess.run(train_init)	# drawing samples from train_data
        total_loss = 0
        n_batches = 0
        try:
            while True:
                _, l = sess.run([optimizer, loss])
                total_loss += l
                n_batches += 1
        except tf.errors.OutOfRangeError:
            pass
        print('Average loss epoch {0}: {1}'.format(i, total_loss/n_batches))
    print('Total time: {0} seconds'.format(time.time() - start_time))

    # test the model
    sess.run(test_init)			# drawing samples from test_data
    total_correct_preds = 0
    try:
        while True:
            accuracy_batch = sess.run(accuracy)
            total_correct_preds += accuracy_batch
    except tf.errors.OutOfRangeError:
        pass

    print('Accuracy {0}'.format(total_correct_preds/n_test))
writer.close()