<a href="https://colab.research.google.com/github/paruliansaragi/DL-Notebooks/blob/master/WesMck_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Numpy Basics: Arrays and Vectorized computation

Because numpy provides an easy C api it can pass data to external libraries written in low-level language. Python the choice language for wrapping legacy C/C++/Fortran codebases. ndarray an effecient multidimensional array for fast array oriented arithmatic operations and flexible broadcasting capabilities. Lin alg, random num generation, fourier transform capabilities.

Numpy is designed for efficiency on large arrays of data. Numpy internally stores data in a contiguous block of memory. 

In [0]:
my_arr = np.arange(1000000)

my_list = list(range(1000000))

In [0]:
%time for _ in range(10): my_arr2 = my_arr *2

CPU times: user 28 ms, sys: 15 ms, total: 43 ms
Wall time: 46.6 ms


In [0]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 723 ms, sys: 273 ms, total: 996 ms
Wall time: 996 ms


# NumPy ndarray: A multidimensional Array Object

ndarray is a fast flexible container for large datasets in Python. Arrays enable you to perform math operations on whole blocks of data. 

In [0]:
data = np.random.randn(2, 3)
data

array([[-1.20792784,  0.18567001,  0.54224762],
       [ 0.16886505, -0.7112716 ,  0.85357102]])

In [0]:
data *10

array([[-12.07927838,   1.85670006,   5.4224762 ],
       [  1.6886505 ,  -7.11271601,   8.53571019]])

In [0]:
data + data

array([[-2.41585568,  0.37134001,  1.08449524],
       [ 0.3377301 , -1.4225432 ,  1.70714204]])

In [0]:
data.shape

(2, 3)

In [0]:
data.dtype

dtype('float64')

In [0]:
#Creating ndarrays
#The easiest way is the array function. This accepts a sequence like object and produces a new NumPy array.
data1 = [6, 7.5, 23, 0.1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5, 23. ,  0.1])

In [0]:
#Nested sequences like a list of lists will be converted to a multi-dimension array
data2 = [[1,2,3], [3,4,5]]
arr2 = np.array(data2)

In [0]:
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [0]:
arr2.ndim

2

In [0]:
arr2.shape

(2, 3)

In [0]:
#np.array tries to find a good default for the dtype object
#zeros and ones create arrays of 0s and 1s. empty creates an array without init its values. 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.empty((2,3,2))#it is not safe to assume empty will return an array of zeros. It may return an array of garbage values like below

array([[[1.1644155e-316, 2.1817433e-316],
        [3.9525252e-323, 2.1817433e-316],
        [3.9525252e-323, 2.1817433e-316]],

       [[4.4465908e-323, 0.0000000e+000],
        [2.1817686e-316, 2.1817686e-316],
        [2.1817686e-316, 0.0000000e+000]]])

In [0]:
#arange is an array-valued version of the range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [0]:
#Data types for ndarrays
#dtype is a special object containing the data type information or metadata, data about data. 
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

arr1.dtype

dtype('float64')

In [0]:
#You can explicity convert or cast an array from one dtype to another using astype method:
float_arr = arr2.astype(np.float32)

In [0]:
float_arr

array([1., 2., 3.], dtype=float32)

In [0]:
int_arr = float_arr.astype(np.int64)

In [0]:
int_arr

array([1, 2, 3])

In [0]:
numeric_str = np.array(['1.2', '3.4', '8.9'], dtype=np.string_)

numeric_str.astype(float)

array([1.2, 3.4, 8.9])

In [0]:
#Arithmetic with Numpy Arrays

arr = np.array([[1.,2.,4.],[7.,2.,4.]])
arr

array([[1., 2., 4.],
       [7., 2., 4.]])

In [0]:
arr * arr

array([[ 1.,  4., 16.],
       [49.,  4., 16.]])

In [0]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#Arithmetic operations with scalars propogate the scalar argument to each element in the array:
1 / arr

array([[1.        , 0.5       , 0.25      ],
       [0.14285714, 0.5       , 0.25      ]])

In [0]:
arr ** 0.5

array([[1.        , 1.41421356, 2.        ],
       [2.64575131, 1.41421356, 2.        ]])

In [0]:
arr2 = np.array([[1.,6.,7],[8,6,3.]])

In [0]:
arr2>arr

array([[False,  True,  True],
       [ True,  True, False]])

**Basic slicing and indexing**

In [0]:
arr = np.arange(10)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5]

5

In [0]:
arr[5:8]

array([5, 6, 7])

In [0]:
arr[5:8]=12

In [0]:
arr#as you can see, if you assign a scalar value to a slice, as in arr[5:8]=12 the value is propogated (or broadcasted henceforth) to the 
#entire selection

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [0]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [0]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [0]:
#the bare [:] will assign to all values in an array:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [0]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [0]:
arr2d[2]

array([7, 8, 9])

In [0]:
arr2d[0][2]

3

In [0]:
arr2d[0,2]

3

axis 0 is the rows and axis 1 is the columns

![alt text](https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png)

In [0]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [0]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
old_vals = arr3d[0].copy()
arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d[0] = old_vals

In [0]:
#arr3d[1, 0] gives you all the values whose indices start with (1, 0) forming a 1d array:
arr3d[1, 0]


array([7, 8, 9])

In [0]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
x[0]

array([7, 8, 9])

In [0]:
x[1, 0]

10

In [0]:
#Indexing with slices
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [0]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [0]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr2d[:2]#as you can see it has sliced along axis 0 the first axis. A slice therefore
#selects a range of elements along an axis. arr2d[:2] = "select the first two rows of arr2d"

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr2d[:2, 1:]#"select the first 2 rows and "

array([[2, 3],
       [5, 6],
       [8, 9]])

In [0]:
arr2d[1, :2]#select first index row and 2 elements

array([4, 5])

In [0]:
arr2d[:3, 2]#select first 3 rows of index number 2

array([3, 6, 9])

In [0]:
# a : by iteself means to entire the entire axis, so you can slice only higher dimensional axes by doing:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [0]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

![alt text](https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346882.png)

**Boolean Indexing**



In [0]:
names  = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Will', 'Joe', 'Bob'])

data = np.random.randn(7, 4)

names

array(['Bob', 'Joe', 'Will', 'Joe', 'Will', 'Joe', 'Bob'], dtype='<U4')

In [0]:
data

array([[ 1.83194486e+00,  2.27110375e-02, -8.81434214e-01,
        -1.08348609e+00],
       [ 9.62616856e-01,  1.04552330e-03, -5.48541335e-01,
         1.06443537e+00],
       [-1.46758676e+00, -1.35579928e-02,  7.40181089e-01,
         1.30940732e+00],
       [ 9.44276598e-01,  5.83295401e-01, -3.32779609e-01,
         1.08462723e+00],
       [-9.81416219e-01,  1.07935453e+00, -6.25801571e-01,
        -4.51190738e-02],
       [-6.12692533e-01,  1.12481723e+00, -3.27927457e-01,
        -2.87009399e-01],
       [ 5.06379314e-01,  2.40641668e+00, -4.17647522e-01,
         1.05538447e+00]])

In [0]:
#Suppose each name corresponds to a row in the data array and we want to select all the rows with corresponding name Bob. 
names == 'Bob'

array([ True, False, False, False, False, False,  True])

In [0]:
data[names == 'Bob']

array([[ 1.83194486,  0.02271104, -0.88143421, -1.08348609],
       [ 0.50637931,  2.40641668, -0.41764752,  1.05538447]])

In [0]:
#The boolean index must me of the same length as the array axis it's indexing
#i select from rows where names ='Bob'

data[names=='Bob', 2:]

array([[-0.88143421, -1.08348609],
       [-0.41764752,  1.05538447]])

In [0]:
names != 'Bob'

array([False,  True,  True,  True,  True,  True, False])

In [0]:
data[~(names == 'Bob')]

array([[ 9.62616856e-01,  1.04552330e-03, -5.48541335e-01,
         1.06443537e+00],
       [-1.46758676e+00, -1.35579928e-02,  7.40181089e-01,
         1.30940732e+00],
       [ 9.44276598e-01,  5.83295401e-01, -3.32779609e-01,
         1.08462723e+00],
       [-9.81416219e-01,  1.07935453e+00, -6.25801571e-01,
        -4.51190738e-02],
       [-6.12692533e-01,  1.12481723e+00, -3.27927457e-01,
        -2.87009399e-01]])

In [0]:
cond = names =='Bob'

data[~cond]

array([[ 9.62616856e-01,  1.04552330e-03, -5.48541335e-01,
         1.06443537e+00],
       [-1.46758676e+00, -1.35579928e-02,  7.40181089e-01,
         1.30940732e+00],
       [ 9.44276598e-01,  5.83295401e-01, -3.32779609e-01,
         1.08462723e+00],
       [-9.81416219e-01,  1.07935453e+00, -6.25801571e-01,
        -4.51190738e-02],
       [-6.12692533e-01,  1.12481723e+00, -3.27927457e-01,
        -2.87009399e-01]])

In [0]:
data[data < 0] = 0 

data

array([[1.83194486e+00, 2.27110375e-02, 0.00000000e+00, 0.00000000e+00],
       [9.62616856e-01, 1.04552330e-03, 0.00000000e+00, 1.06443537e+00],
       [0.00000000e+00, 0.00000000e+00, 7.40181089e-01, 1.30940732e+00],
       [9.44276598e-01, 5.83295401e-01, 0.00000000e+00, 1.08462723e+00],
       [0.00000000e+00, 1.07935453e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.12481723e+00, 0.00000000e+00, 0.00000000e+00],
       [5.06379314e-01, 2.40641668e+00, 0.00000000e+00, 1.05538447e+00]])

In [0]:
data.dtype

dtype('float64')

In [0]:
#Fancy indexing
#describes indexing using integer arrays. Suppose we had a 8x4 array:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i 

In [0]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [0]:
#Transposing Arrays and Swapping axes

arr = np.arange(15).reshape((3, 5))

In [0]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [0]:
arr = np.random.randn(6, 3)

arr

array([[-0.88212445, -0.70497083,  0.76781104],
       [-0.83269036,  2.42587435,  0.27780698],
       [-0.29965915, -1.41192965, -0.27031827],
       [ 1.27682099,  0.59457731, -0.77495065],
       [-1.55281717,  0.7794505 , -0.678358  ],
       [-1.31408036, -0.82394953, -1.39863763]])

In [0]:
np.dot(arr.T, arr)

array([[ 7.32963257, -0.34347198,  1.07418618],
       [-0.34347198, 10.01535367,  0.67720308],
       [ 1.07418618,  0.67720308,  3.75668779]])

In [0]:
#for higher d arrays, tranpose will accept a tuple of axis numbers to permute the axes
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
arr.transpose((1,0,2))#here the axes have been reordere with the second axis first, the first axis second and the last axis unchanged

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [0]:
#np has a special method swapaxes which takes a pair of axis numbers and switches the indicated axes to rearrange the data:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast element wise array functions

a universal function or ufunc is a function that performs element-wise operations on data in ndarrays. Fast vectorized wrappers for simple functions. Many ufuncs are simple element wise transformations like sqrt or exp:

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [0]:
#these are unary ufuncs, others such as add or maximum take two arrays thus binary ufuncs and retun a single array:
x = np.random.randn(8)
y = np.random.randn(8)

In [0]:
x

array([-1.82651956, -0.68184618, -0.56565683, -0.79613063, -0.02023656,
        0.02010387,  0.718671  ,  0.02692442])

In [0]:
np.maximum(x, y)#here maximum computed the element wise max of the elements in x and y

array([-0.92630533, -0.54555907, -0.56565683,  0.02949607,  1.32764607,
        0.02010387,  0.718671  ,  1.09701201])

In [0]:
#divmod returns the fractional and integral parts of a floating point array:
arr = np.random.randn(7) * 5
arr

array([ 3.61633191, -4.19660449,  8.85093686, -4.41138478, -6.21359158,
        8.11919472,  7.48197062])

In [0]:
remainder, whole_part = np.modf(arr)

In [0]:
remainder

array([ 0.61633191, -0.19660449,  0.85093686, -0.41138478, -0.21359158,
        0.11919472,  0.48197062])

In [0]:
whole_part

array([ 3., -4.,  8., -4., -6.,  8.,  7.])

In [0]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    x -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-z))
    #s = 1 /(1+ (np.exp(-z)))
    ### END CODE HERE ###
    
    return s

In [0]:
sigmoid(4)

0.9820137900379085

In [0]:
# GRADED FUNCTION: initialize_with_zeros

def initialize_with_zeros(dim):
    """
    This function creates a vector of zeros of shape (dim, 1) for w and initializes b to 0.
    
    Argument:
    dim -- size of the w vector we want (or number of parameters in this case)
    
    Returns:
    w -- initialized vector of shape (dim, 1)
    b -- initialized scalar (corresponds to the bias)
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    w = np.zeros(shape=(dim, 1))
    b = 0
    ### END CODE HERE ###

    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [0]:
initialize_with_zeros(2)

(array([[0.],
        [0.]]), 0)

In [0]:
def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    cost -- negative log-likelihood cost for logistic regression
    dw -- gradient of the loss with respect to w, thus same shape as w
    db -- gradient of the loss with respect to b, thus same shape as b
    
    Tips:
    - Write your code step by step for the propagation
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    ### START CODE HERE ### (≈ 2 lines of code)
    #A = sigmoid(z) 
    #Z = np.dot(w.T, x) + b
    Z = np.dot(w.T, X) + b
    A = sigmoid(Z)# A = y hat
    cost = (- 1 / m) * np.sum(Y * np.log(A) + (1 - Y) * (np.log(1 - A)))
    ### END CODE HERE ###
    
    # BACKWARD PROPAGATION (TO FIND GRAD)
    ### START CODE HERE ### (≈ 2 lines of code)
    #Backprop - compute the derivatives
    dw = (1 / m) * np.dot(X, (A - Y).T)
    db = (1 / m) * np.sum(A - Y)
    ### END CODE HERE ###
    
    
    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [0]:
w, b, X, Y = np.array([[1], [2]]), 2, np.array([[1,2], [3,4]]), np.array([[1, 0]])
grads, cost = propagate(w, b, X, Y)
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))
print ("cost = " + str(cost))

dw = [[0.99993216]
 [1.99980262]]
db = 0.49993523062470574
cost = 6.000064773192205


In [0]:
# GRADED FUNCTION: optimize

def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    """
    This function optimizes w and b by running a gradient descent algorithm
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of shape (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat), of shape (1, number of examples)
    num_iterations -- number of iterations of the optimization loop
    learning_rate -- learning rate of the gradient descent update rule
    print_cost -- True to print the loss every 100 steps
    
    Returns:
    params -- dictionary containing the weights w and bias b
    grads -- dictionary containing the gradients of the weights and bias with respect to the cost function
    costs -- list of all the costs computed during the optimization, this will be used to plot the learning curve.
    
    Tips:
    You basically need to write down two steps and iterate through them:
        1) Calculate the cost and the gradient for the current parameters. Use propagate().
        2) Update the parameters using gradient descent rule for w and b.
    """
    
    costs = []
    
    for i in range(num_iterations):
        
        
        # Cost and gradient calculation (≈ 1-4 lines of code)
        ### START CODE HERE ### 
        grads, cost = propagate(w, b, X, Y)
        ### END CODE HERE ###
        
        # Retrieve derivatives from grads
        dw = grads["dw"]
        db = grads["db"]
        
        # update rule (≈ 2 lines of code)
        ### START CODE HERE ###
        w = w - learning_rate * dw
        b = b - learning_rate * db        
        ### END CODE HERE ###
        
        # Record the costs
        if i % 100 == 0:
            costs.append(cost)
        
        # Print the cost every 100 training examples
        if print_cost and i % 100 == 0:
            print ("Cost after iteration %i: %f" % (i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [0]:
params, grads, costs = optimize(w, b, X, Y, num_iterations= 100, learning_rate = 0.009, print_cost = False)

print ("w = " + str(params["w"]))
print ("b = " + str(params["b"]))
print ("dw = " + str(grads["dw"]))
print ("db = " + str(grads["db"]))

w = [[0.1124579 ]
 [0.23106775]]
b = 1.5593049248448891
dw = [[0.90158428]
 [1.76250842]]
db = 0.4304620716786828


In [0]:
# GRADED FUNCTION: predict

def predict(w, b, X):
    '''
    Predict whether the label is 0 or 1 using learned logistic regression parameters (w, b)
    
    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    
    Returns:
    Y_prediction -- a numpy array (vector) containing all predictions (0/1) for the examples in X
    '''
    
    m = X.shape[1]
    Y_prediction = np.zeros((1, m))
    w = w.reshape(X.shape[0], 1)
    
    # Compute vector "A" predicting the probabilities of a cat being present in the picture
    ### START CODE HERE ### (≈ 1 line of code)
    A = sigmoid(np.dot(w.T, X)+ b)
    ### END CODE HERE ###
    
    for i in range(A.shape[1]):
        # Convert probabilities a[0,i] to actual predictions p[0,i]
        ### START CODE HERE ### (≈ 4 lines of code)
        Y_prediction[0, 1] = 1 if A[0, 1] > 0.5 else 0
        ### END CODE HERE ###
    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [0]:
print("predictions = " + str(predict(w, b, X)))

predictions = [[0. 1.]]


In [0]:
# GRADED FUNCTION: model

def model(X_train, Y_train, X_test, Y_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
    """
    Builds the logistic regression model by calling the function you've implemented previously
    
    Arguments:
    X_train -- training set represented by a numpy array of shape (num_px * num_px * 3, m_train)
    Y_train -- training labels represented by a numpy array (vector) of shape (1, m_train)
    X_test -- test set represented by a numpy array of shape (num_px * num_px * 3, m_test)
    Y_test -- test labels represented by a numpy array (vector) of shape (1, m_test)
    num_iterations -- hyperparameter representing the number of iterations to optimize the parameters
    learning_rate -- hyperparameter representing the learning rate used in the update rule of optimize()
    print_cost -- Set to true to print the cost every 100 iterations
    
    Returns:
    d -- dictionary containing information about the model.
    """
    
    ### START CODE HERE ###
    # initialize parameters with zeros (≈ 1 line of code)
    w, b = initialize_with_zeros(X_train.shape[0])

    # Gradient descent (≈ 1 line of code)
    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
    
    # Retrieve parameters w and b from dictionary "parameters"
    w = parameters["w"]
    b = parameters["b"]
    
    # Predict test/train set examples (≈ 2 lines of code)
    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    ### END CODE HERE ###

    # Print train/test Errors
    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [0]:
d = model(X_flatten, X_flatten, y_flatten, y_flatten, num_iterations = 2000, learning_rate = 0.005, print_cost = True)